### ISSUE TITLE
15 character limit

### ISSUE THREAD

**Issue by hipposec** [primaryobjects/vpndemon#5]
Just a suggestion, you may want to advise the user that there is a 15 character limit in the process to be killed. Transmission, the default torrent client in Ubuntu shows up as "transmission-gtk" in the process list. However, putting that into vpndemon will not result result in transmission being killed on disconnect because pgrep has a 15 character limit and thus will not return the PID.

**Comment by primaryobjects** [comment]
Thank you for the tip! Please feel free to fork and issue a PR if there is a fix. Thanks. :)
