### ISSUE TITLE
Can't specify a process name anymore

### ISSUE THREAD

**Issue by becheesus** [primaryobjects/vpndemon#6]
Hi,

since today it is no longer possible to specify a process name. The message "No process name entered" is displayed. The output on the console is: "./vpndemon.sh: line 33: [: too many arguments".

In the meantime I had done a system update (Arch Linux) but didn't change anything manually since the last time I used the script.

Unfortunately, I have no idea what exactly might have changed here or how I could fix this error myself, so I wanted to ask here.

**Comment by becheesus** [comment]
Addition: it is still possible to pass the process name directly as an argument on the command line.

**Comment by primaryobjects** [comment]
Thank you for the notice.

Does this refer to the line of code that retrieves the process ID by (name)https://github.com/primaryobjects/vpndemon/blob/master/vpndemon.sh#L70)?

I would recommend trying the line of code manually, and substituting in values, to see output from the command.

Please feel free to fork and issue a PR if there is a fix in the script to merge. Thanks. :)

**Comment by becheesus** [comment]
In the meantime the problem has been resolved by itself (per system update...).

Please excuse my hastiness. I've learned a little about Bash, though.
